
spring:
  profiles:
    active:
    - dev
---
spring:
  profiles:
    active: dev
    aplication:
      name: microservicecloud-config-dev
---
spring:
  profiles:
    active: test
    aplication:
      name: microservicecloud-config-test