spring:
  profiles:
    active:
      - dev
---
server:
  port: 7001
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dev

---
server:
  port: 7002
spring:
  profiles: test
  application:
    name: microservicecloud-config-test
